from cloud_watch_functionalities import *
from ec2_functionalities import *
from emr_functionalities import *
from iam_functionalities import *
from lambda_functionalities import *
from rds_functionalities import *
from s3_functionalities import *
from sns_functionalities import *
from sqs_functionalities import *